/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_quanta_qtalk_media_audio_AudioStreamEngineTransform */

#ifndef _Included_com_quanta_qtalk_media_audio_AudioStreamEngineTransform
#define _Included_com_quanta_qtalk_media_audio_AudioStreamEngineTransform
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_quanta_qtalk_media_audio_AudioStreamEngineTransform
 * Method:    _SetReportCB
 * Signature: (ILcom/quanta/qtalk/media/audio/IAudioStreamReportCB;)V
 */
JNIEXPORT void JNICALL Java_com_quanta_qtalk_media_audio_AudioStreamEngineTransform__1SetReportCB
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     com_quanta_qtalk_media_audio_AudioStreamEngineTransform
 * Method:    _Start
 * Signature: (JLcom/quanta/qtalk/media/audio/IAudioSink;ILjava/lang/String;IIILjava/lang/String;IIIIZLjava/lang/String;Ljava/lang/String;IZII)I
 */
JNIEXPORT jint JNICALL Java_com_quanta_qtalk_media_audio_AudioStreamEngineTransform__1Start
  (JNIEnv *, jclass, jlong, jobject, jint, jstring, jint, jint, jint, jstring, jint, jint, jint, jint, jboolean, jstring, jstring, jint, jboolean, jint, jint);

/*
 * Class:     com_quanta_qtalk_media_audio_AudioStreamEngineTransform
 * Method:    _Stop
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_quanta_qtalk_media_audio_AudioStreamEngineTransform__1Stop
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_quanta_qtalk_media_audio_AudioStreamEngineTransform
 * Method:    _GetSSRC
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_quanta_qtalk_media_audio_AudioStreamEngineTransform__1GetSSRC
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_quanta_qtalk_media_audio_AudioStreamEngineTransform
 * Method:    _OnSendDirect
 * Signature: (ILjava/nio/ByteBuffer;IJI)V
 */
JNIEXPORT void JNICALL Java_com_quanta_qtalk_media_audio_AudioStreamEngineTransform__1OnSendDirect
  (JNIEnv *, jclass, jint, jobject, jint, jlong, jint);

/*
 * Class:     com_quanta_qtalk_media_audio_AudioStreamEngineTransform
 * Method:    _OnSend
 * Signature: (I[BIJI)V
 */
JNIEXPORT void JNICALL Java_com_quanta_qtalk_media_audio_AudioStreamEngineTransform__1OnSend
  (JNIEnv *, jclass, jint, jbyteArray, jint, jlong, jint);

/*
 * Class:     com_quanta_qtalk_media_audio_AudioStreamEngineTransform
 * Method:    _SetHold
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_com_quanta_qtalk_media_audio_AudioStreamEngineTransform__1SetHold
  (JNIEnv *, jclass, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
