/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_quanta_qtalk_media_audio_OpusEncoderTransform */

#ifndef _Included_com_quanta_qtalk_media_audio_OpusEncoderTransform
#define _Included_com_quanta_qtalk_media_audio_OpusEncoderTransform
#ifdef __cplusplus
extern "C" {
#endif
#undef com_quanta_qtalk_media_audio_OpusEncoderTransform_DEFAULT_ID
#define com_quanta_qtalk_media_audio_OpusEncoderTransform_DEFAULT_ID 111L
#undef com_quanta_qtalk_media_audio_OpusEncoderTransform_mInFormat
#define com_quanta_qtalk_media_audio_OpusEncoderTransform_mInFormat 255L
#undef com_quanta_qtalk_media_audio_OpusEncoderTransform_mOutFormat
#define com_quanta_qtalk_media_audio_OpusEncoderTransform_mOutFormat 111L
#undef com_quanta_qtalk_media_audio_OpusEncoderTransform_mCompression
#define com_quanta_qtalk_media_audio_OpusEncoderTransform_mCompression 3L
/*
 * Class:     com_quanta_qtalk_media_audio_OpusEncoderTransform
 * Method:    _Start
 * Signature: (Lcom/quanta/qtalk/media/audio/IAudioSink;III)I
 */
JNIEXPORT jint JNICALL Java_com_quanta_qtalk_media_audio_OpusEncoderTransform__1Start
  (JNIEnv *, jclass, jobject, jint, jint, jint);

/*
 * Class:     com_quanta_qtalk_media_audio_OpusEncoderTransform
 * Method:    _Stop
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_quanta_qtalk_media_audio_OpusEncoderTransform__1Stop
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_quanta_qtalk_media_audio_OpusEncoderTransform
 * Method:    _OnMedia
 * Signature: (I[SIJ)V
 */
JNIEXPORT void JNICALL Java_com_quanta_qtalk_media_audio_OpusEncoderTransform__1OnMedia
  (JNIEnv *, jclass, jint, jshortArray, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
