/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_quanta_qtalk_sr2_SR2_SoundServer */

#ifndef _Included_com_quanta_qtalk_sr2_SR2_SoundServer
#define _Included_com_quanta_qtalk_sr2_SR2_SoundServer
#ifdef __cplusplus
extern "C" {
#endif
#undef com_quanta_qtalk_sr2_SR2_SoundServer_PLAYSTATE_PLAYING
#define com_quanta_qtalk_sr2_SR2_SoundServer_PLAYSTATE_PLAYING 3L
#undef com_quanta_qtalk_sr2_SR2_SoundServer_PLAYSTATE_STOPPED
#define com_quanta_qtalk_sr2_SR2_SoundServer_PLAYSTATE_STOPPED 1L
#undef com_quanta_qtalk_sr2_SR2_SoundServer_PLAYSTATE_PAUSED
#define com_quanta_qtalk_sr2_SR2_SoundServer_PLAYSTATE_PAUSED 2L
/*
 * Class:     com_quanta_qtalk_sr2_SR2_SoundServer
 * Method:    SpeexEchoPlayback
 * Signature: ([S)V
 */
JNIEXPORT void JNICALL Java_com_quanta_qtalk_sr2_SR2_1SoundServer_SpeexEchoPlayback
  (JNIEnv *, jobject, jshortArray);

#ifdef __cplusplus
}
#endif
#endif
