/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_quanta_qtalk_media_video_H264DecodeTransform */

#ifndef _Included_com_quanta_qtalk_media_video_H264DecodeTransform
#define _Included_com_quanta_qtalk_media_video_H264DecodeTransform
#ifdef __cplusplus
extern "C" {
#endif
#undef com_quanta_qtalk_media_video_H264DecodeTransform_DEFAULT_ID
#define com_quanta_qtalk_media_video_H264DecodeTransform_DEFAULT_ID 109L
/*
 * Class:     com_quanta_qtalk_media_video_H264DecodeTransform
 * Method:    _Start
 * Signature: (Lcom/quanta/qtalk/media/video/IVideoSink;II)I
 */
JNIEXPORT jint JNICALL Java_com_quanta_qtalk_media_video_H264DecodeTransform__1Start
  (JNIEnv *, jclass, jobject, jint, jint);

/*
 * Class:     com_quanta_qtalk_media_video_H264DecodeTransform
 * Method:    _Stop
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_quanta_qtalk_media_video_H264DecodeTransform__1Stop
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_quanta_qtalk_media_video_H264DecodeTransform
 * Method:    _OnMedia
 * Signature: (ILjava/nio/ByteBuffer;IJS)I
 */
JNIEXPORT jint JNICALL Java_com_quanta_qtalk_media_video_H264DecodeTransform__1OnMedia
  (JNIEnv *, jclass, jint, jobject, jint, jlong, jshort);

/*
 * Class:     com_quanta_qtalk_media_video_H264DecodeTransform
 * Method:    _Decode
 * Signature: (I[BI[BI)I
 */
JNIEXPORT jint JNICALL Java_com_quanta_qtalk_media_video_H264DecodeTransform__1Decode
  (JNIEnv *, jclass, jint, jbyteArray, jint, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_quanta_qtalk_media_video_H264DecodeTransform_H264Data */

#ifndef _Included_com_quanta_qtalk_media_video_H264DecodeTransform_H264Data
#define _Included_com_quanta_qtalk_media_video_H264DecodeTransform_H264Data
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_quanta_qtalk_media_video_H264DecodeTransform_H264DataDepository */

#ifndef _Included_com_quanta_qtalk_media_video_H264DecodeTransform_H264DataDepository
#define _Included_com_quanta_qtalk_media_video_H264DecodeTransform_H264DataDepository
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
