/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_quanta_qtalk_media_video_X264Transform */

#ifndef _Included_com_quanta_qtalk_media_video_X264Transform
#define _Included_com_quanta_qtalk_media_video_X264Transform
#ifdef __cplusplus
extern "C" {
#endif
#undef com_quanta_qtalk_media_video_X264Transform_DEFAULT_ID
#define com_quanta_qtalk_media_video_X264Transform_DEFAULT_ID 109L
/*
 * Class:     com_quanta_qtalk_media_video_X264Transform
 * Method:    _Start
 * Signature: (Lcom/quanta/qtalk/media/ISink;III)I
 */
JNIEXPORT jint JNICALL Java_com_quanta_qtalk_media_video_X264Transform__1Start
  (JNIEnv *, jclass, jobject, jint, jint, jint);

/*
 * Class:     com_quanta_qtalk_media_video_X264Transform
 * Method:    _Stop
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_quanta_qtalk_media_video_X264Transform__1Stop
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_quanta_qtalk_media_video_X264Transform
 * Method:    _OnMedia
 * Signature: (I[BIJS)V
 */
JNIEXPORT void JNICALL Java_com_quanta_qtalk_media_video_X264Transform__1OnMedia
  (JNIEnv *, jclass, jint, jbyteArray, jint, jlong, jshort);

/*
 * Class:     com_quanta_qtalk_media_video_X264Transform
 * Method:    _OnMediaDirect
 * Signature: (ILjava/nio/ByteBuffer;IJS)V
 */
JNIEXPORT void JNICALL Java_com_quanta_qtalk_media_video_X264Transform__1OnMediaDirect
  (JNIEnv *, jclass, jint, jobject, jint, jlong, jshort);

/*
 * Class:     com_quanta_qtalk_media_video_X264Transform
 * Method:    _SetGop
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_quanta_qtalk_media_video_X264Transform__1SetGop
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_quanta_qtalk_media_video_X264Transform
 * Method:    _SetBitRate
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_quanta_qtalk_media_video_X264Transform__1SetBitRate
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
