/* src/config.h.  Generated by configure.  */
/* src/config.h.in.  Generated from configure.in by autoheader.  */
/*
 * Define this if we have the TFRC library
 */
/* #undef HAVE_TFRC */

/*
 * Define this if we have a functional Tcl/Tk distribution
 */
/* #undef HAVE_TCL_TK */

/*
 * Define this if we have SDL
 */

// comment by willy, 2010-07-07
//#define HAVE_LIBSDL 1

/*
 * Define this if we have a Darwin enviroment
 */
/* #undef HAVE_DARWIN */

/*
 * Define this if we have a Cocoa UI
 */
/* #undef HAVE_COCOA */

/*
 * Define this if you want IPv6 support.
 */
/* #undef HAVE_IPv6 */

/*
 * Define this is you have a DVS HDstation card
 */
/* #undef HAVE_HDSTATION */

/* Audio device related */
/* #undef HAVE_MACOSX_AUDIO */
/* #undef HAVE_SPARC_AUDIO */
/* #undef HAVE_SGI_AUDIO */
/* #undef HAVE_PCA_AUDIO */
/* #undef HAVE_LUIGI_AUDIO */
/* #undef HAVE_NEWPCM_AUDIO */

// comment by willy, 2010-07-07
//#define HAVE_OSS_AUDIO 1

/* #undef HAVE_HP_AUDIO */
/* #undef HAVE_NETBSD_AUDIO */
/* #undef HAVE_OSPREY_AUDIO */
/* #undef HAVE_MACHINE_PCAUDIOIO_H */

// comment by willy, 2010-07-07
//#define HAVE_ALSA_AUDIO 1
//#define HAVE_IXJ_AUDIO 1

/* GSM related */

// comment by willy, 2010-07-07
//#define SASR 1
//#define FAST 1
//#define USE_FLOAT_MUL 1

/* FireWire and DV */
/* #undef HAVE_FIREWIRE_DV_FREEBSD */
/* #undef HAVE_FIREWIRE_DV_LINUX */
/* #undef HAVE_DV_CODEC */

/*
 * If you don't have these types in <inttypes.h>, #define these to be
 * the types you do have.
 */
/* #undef int8_t */
/* #undef int16_t */
/* #undef int32_t */
/* #undef int64_t */
/* #undef uint8_t */
/* #undef uint16_t */
/* #undef uint32_t */

/*
 * Debugging:
 * DEBUG: general debugging
 * DEBUG_MEM: debug memory allocation
 */
/* #undef DEBUG */
/* #undef DEBUG_MEM */


/* Define to 1 if you have the `inet_ntop' function. */
// comment by willy, 2010-07-07
//#define HAVE_INET_NTOP 1

/* Define to 1 if you have the `inet_pton' function. */
// comment by willy, 2010-07-07
//#define HAVE_INET_PTON 1

/* Define to 1 if you have the <inttypes.h> header file. */
// comment by willy, 2010-07-07
//#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the `dv' library (-ldv). */
/* #undef HAVE_LIBDV */

/* Define to 1 if you have the `madvise' function. */
// comment by willy, 2010-07-07
//#define HAVE_MADVISE 1

/* Define to 1 if you have the <memory.h> header file. */
// comment by willy, 2010-07-07
//#define HAVE_MEMORY_H 1

/* Define to 1 if you have the <SDL11/SDL.h> header file. */
/* #undef HAVE_SDL11_SDL_H */

/* Define to 1 if you have the <SDL/SDL.h> header file. */

// comment by willy, 2010-07-07
//#define HAVE_SDL_SDL_H 1

/* Define to 1 if you have the <soundcard.h> header file. */
/* #undef HAVE_SOUNDCARD_H */

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <stropts.h> header file. */
//#define HAVE_STROPTS_H 1

/* Define to 1 if you have the <sys/filio.h> header file. */
/* #undef HAVE_SYS_FILIO_H */

/* Define to 1 if you have the <sys/soundcard.h> header file. */
// comment by willy, 2010-07-07
//#define HAVE_SYS_SOUNDCARD_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <sys/wait.h> header file. */
#define HAVE_SYS_WAIT_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define to 1 if you have the `vsnprintf' function. */
#define HAVE_VSNPRINTF 1

/* Define to the address where bug reports for this package should be sent. */
#undef PACKAGE_BUGREPORT

/* Define to the full name of this package. */
#undef PACKAGE_NAME

/* Define to the full name and version of this package. */
#undef PACKAGE_STRING

/* Define to the one symbol short name of this package. */
#undef PACKAGE_TARNAME

/* Define to the version of this package. */
#undef PACKAGE_VERSION

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Define to 1 if your processor stores words with the most significant byte
   first (like Motorola and SPARC, unlike Intel and VAX). */
/* #undef WORDS_BIGENDIAN */

/* Define to 1 if the X Window System is missing or not being used. */
/* #undef X_DISPLAY_MISSING */

/* Define to 1 if type `char' is unsigned and you are not using gcc.  */
#ifndef __CHAR_UNSIGNED__
/* # undef __CHAR_UNSIGNED__ */
#endif

/* Define to empty if `const' does not conform to ANSI C. */
/* #undef const */

/* Define to `__inline__' or `__inline' if that's what the C compiler
   calls it, or to nothing if 'inline' is not supported under any name.  */
#ifndef __cplusplus
/* #undef inline */
#endif

/* Define to `short' if <sys/types.h> does not define. */
/* #undef int16_t */

/* Define to `long' if <sys/types.h> does not define. */
/* #undef int32_t */

/* Define to `long long' if <sys/types.h> does not define. */
/* #undef int64_t */

/* Define to `signed char' if <sys/types.h> does not define. */
/* #undef int8_t */

/* Define to `unsigned' if <sys/types.h> does not define. */
/* #undef size_t */

/* Define to `unsigned short' if <sys/types.h> does not define. */
/* #undef uint16_t */

/* Define to `unsigned int' if <sys/types.h> does not define. */
/* #undef uint32_t */

/* Define to `unsigned char' if <sys/types.h> does not define. */
/* #undef uint8_t */

// comment by willy, 2010-07-07
//#ifndef WORDS_BIGENDIAN
//#define WORDS_SMALLENDIAN
//#endif

