#!/usr/bin/perl -w
use File::Path;
#die "usage: an argument for dir name" unless @ARGV == 1;
@ARGV = qw/modifiedVersion/ if @ARGV == 0;

if(-d $ARGV[0])
{
	print "dir exists, remove the old one? (Y/n)";
	$_ = <STDIN>;
	exit 0 if /^n$/i;

	rmtree($ARGV[0]);
	print "Remove complete\n";
}
mkdir $ARGV[0], 0755 or die "make dir fail: $!";

my $dirToProcess = ".";
opendir DH, $dirToProcess or die "can not open $dirToProcess: $!";
foreach $file (readdir DH)
{
	next if (-d $file);
	open FILE, "< $file" or die "open reading file error: $!" ;
	open OUTPUT, "> $ARGV[0]/$file" or die "open writing file error:$!";

	my $count = 0;

	while(<FILE>){
		if(/pthread_mutex_(unlock|lock)\([\s]*&([\S]*)[\s]*\)/)
		{
			print OUTPUT "#if MUTEX_DEBUG\n";
			print OUTPUT "    printf(\"pthread_mutex_$1 for %s at %s Line:%d %s\",\"$2\",__FILE__,__LINE__,__FUNCTION__);\n";
			print OUTPUT "#endif\n";
			
			$count ++;
		}
		print OUTPUT $_;
	}

	print "$count operations are done in $file.\n" if $count>0;
}
closedir DH;
