/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_quanta_qtalk_call_engine_NativeCallEngine */

#ifndef _Included_com_quanta_qtalk_call_engine_NativeCallEngine
#define _Included_com_quanta_qtalk_call_engine_NativeCallEngine
#ifdef __cplusplus
extern "C" {
#endif
#undef com_quanta_qtalk_call_engine_NativeCallEngine_MYDEBUG
#define com_quanta_qtalk_call_engine_NativeCallEngine_MYDEBUG 1L
/*
 * Class:     com_quanta_qtalk_call_engine_NativeCallEngine
 * Method:    _createEngine
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_quanta_qtalk_call_engine_NativeCallEngine__1createEngine
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     com_quanta_qtalk_call_engine_NativeCallEngine
 * Method:    _destroyEngine
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_quanta_qtalk_call_engine_NativeCallEngine__1destroyEngine
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_quanta_qtalk_call_engine_NativeCallEngine
 * Method:    _login
 * Signature: (ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;ILcom/quanta/qtalk/call/ICallEngineListener;Ljava/lang/String;Ljava/lang/String;ZI)V
 */
JNIEXPORT void JNICALL Java_com_quanta_qtalk_call_engine_NativeCallEngine__1login
  (JNIEnv *, jclass, jint, jstring, jstring, jstring, jint, jstring, jstring, jstring, jint, jobject, jstring, jstring, jboolean, jint);

/*
 * Class:     com_quanta_qtalk_call_engine_NativeCallEngine
 * Method:    _logout
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_quanta_qtalk_call_engine_NativeCallEngine__1logout
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_quanta_qtalk_call_engine_NativeCallEngine
 * Method:    _setCapability
 * Signature: (I[Lcom/quanta/qtalk/call/MDP;[Lcom/quanta/qtalk/call/MDP;III)V
 */
JNIEXPORT void JNICALL Java_com_quanta_qtalk_call_engine_NativeCallEngine__1setCapability
  (JNIEnv *, jclass, jint, jobjectArray, jobjectArray, jint, jint, jint);

/*
 * Class:     com_quanta_qtalk_call_engine_NativeCallEngine
 * Method:    _makeCall
 * Signature: (IILjava/lang/String;Ljava/lang/String;Ljava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_com_quanta_qtalk_call_engine_NativeCallEngine__1makeCall
  (JNIEnv *, jclass, jint, jint, jstring, jstring, jstring, jint, jint);

/*
 * Class:     com_quanta_qtalk_call_engine_NativeCallEngine
 * Method:    _sequentialMakeCall
 * Signature: (IILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_com_quanta_qtalk_call_engine_NativeCallEngine__1sequentialMakeCall
  (JNIEnv *, jclass, jint, jint, jstring, jstring, jstring, jstring, jint, jint);

/*
 * Class:     com_quanta_qtalk_call_engine_NativeCallEngine
 * Method:    _acceptCall
 * Signature: (IILjava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_com_quanta_qtalk_call_engine_NativeCallEngine__1acceptCall
  (JNIEnv *, jclass, jint, jint, jstring, jint, jint);

/*
 * Class:     com_quanta_qtalk_call_engine_NativeCallEngine
 * Method:    _hangupCall
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_quanta_qtalk_call_engine_NativeCallEngine__1hangupCall
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_quanta_qtalk_call_engine_NativeCallEngine
 * Method:    _keepAlive
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_quanta_qtalk_call_engine_NativeCallEngine__1keepAlive
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_quanta_qtalk_call_engine_NativeCallEngine
 * Method:    _requestIDR
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_quanta_qtalk_call_engine_NativeCallEngine__1requestIDR
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_quanta_qtalk_call_engine_NativeCallEngine
 * Method:    networkInterfaceSwitch
 * Signature: (ILjava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_com_quanta_qtalk_call_engine_NativeCallEngine_networkInterfaceSwitch
  (JNIEnv *, jclass, jint, jstring, jint, jint);

/*
 * Class:     com_quanta_qtalk_call_engine_NativeCallEngine
 * Method:    _SwitchCallToPX
 * Signature: (IILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_quanta_qtalk_call_engine_NativeCallEngine__1SwitchCallToPX
  (JNIEnv *, jclass, jint, jint, jstring);

/*
 * Class:     com_quanta_qtalk_call_engine_NativeCallEngine
 * Method:    _SetQTDND
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_quanta_qtalk_call_engine_NativeCallEngine__1SetQTDND
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_quanta_qtalk_call_engine_NativeCallEngine
 * Method:    _setProvision
 * Signature: (ILcom/quanta/qtalk/provision/ProvisionUtility/ProvisionInfo;)V
 */
JNIEXPORT void JNICALL Java_com_quanta_qtalk_call_engine_NativeCallEngine__1setProvision
  (JNIEnv *, jclass, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
