/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ffmpeg_service_FFMpegHandler */

#ifndef _Included_org_ffmpeg_service_FFMpegHandler
#define _Included_org_ffmpeg_service_FFMpegHandler
#ifdef __cplusplus
extern "C" {
#endif
#undef org_ffmpeg_service_FFMpegHandler_COUNT_FRAME
#define org_ffmpeg_service_FFMpegHandler_COUNT_FRAME 0L
/*
 * Class:     org_ffmpeg_service_FFMpegHandler
 * Method:    _Start
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_org_ffmpeg_service_FFMpegHandler__1Start
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     org_ffmpeg_service_FFMpegHandler
 * Method:    _Stop
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_ffmpeg_service_FFMpegHandler__1Stop
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_ffmpeg_service_FFMpegHandler
 * Method:    _OnMedia
 * Signature: (I[BIS)I
 */
JNIEXPORT jint JNICALL Java_org_ffmpeg_service_FFMpegHandler__1OnMedia
  (JNIEnv *, jclass, jint, jbyteArray, jint, jshort);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_ffmpeg_service_FFMpegHandler_DecodeThread */

#ifndef _Included_org_ffmpeg_service_FFMpegHandler_DecodeThread
#define _Included_org_ffmpeg_service_FFMpegHandler_DecodeThread
#ifdef __cplusplus
extern "C" {
#endif
#undef org_ffmpeg_service_FFMpegHandler_DecodeThread_MIN_PRIORITY
#define org_ffmpeg_service_FFMpegHandler_DecodeThread_MIN_PRIORITY 1L
#undef org_ffmpeg_service_FFMpegHandler_DecodeThread_NORM_PRIORITY
#define org_ffmpeg_service_FFMpegHandler_DecodeThread_NORM_PRIORITY 5L
#undef org_ffmpeg_service_FFMpegHandler_DecodeThread_MAX_PRIORITY
#define org_ffmpeg_service_FFMpegHandler_DecodeThread_MAX_PRIORITY 10L
#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_ffmpeg_service_FFMpegHandler_DestoryThread */

#ifndef _Included_org_ffmpeg_service_FFMpegHandler_DestoryThread
#define _Included_org_ffmpeg_service_FFMpegHandler_DestoryThread
#ifdef __cplusplus
extern "C" {
#endif
#undef org_ffmpeg_service_FFMpegHandler_DestoryThread_MIN_PRIORITY
#define org_ffmpeg_service_FFMpegHandler_DestoryThread_MIN_PRIORITY 1L
#undef org_ffmpeg_service_FFMpegHandler_DestoryThread_NORM_PRIORITY
#define org_ffmpeg_service_FFMpegHandler_DestoryThread_NORM_PRIORITY 5L
#undef org_ffmpeg_service_FFMpegHandler_DestoryThread_MAX_PRIORITY
#define org_ffmpeg_service_FFMpegHandler_DestoryThread_MAX_PRIORITY 10L
#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_ffmpeg_service_FFMpegHandler_H264Data */

#ifndef _Included_org_ffmpeg_service_FFMpegHandler_H264Data
#define _Included_org_ffmpeg_service_FFMpegHandler_H264Data
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_ffmpeg_service_FFMpegHandler_H264DataDepository */

#ifndef _Included_org_ffmpeg_service_FFMpegHandler_H264DataDepository
#define _Included_org_ffmpeg_service_FFMpegHandler_H264DataDepository
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_ffmpeg_service_FFMpegHandler_ReadThread */

#ifndef _Included_org_ffmpeg_service_FFMpegHandler_ReadThread
#define _Included_org_ffmpeg_service_FFMpegHandler_ReadThread
#ifdef __cplusplus
extern "C" {
#endif
#undef org_ffmpeg_service_FFMpegHandler_ReadThread_MIN_PRIORITY
#define org_ffmpeg_service_FFMpegHandler_ReadThread_MIN_PRIORITY 1L
#undef org_ffmpeg_service_FFMpegHandler_ReadThread_NORM_PRIORITY
#define org_ffmpeg_service_FFMpegHandler_ReadThread_NORM_PRIORITY 5L
#undef org_ffmpeg_service_FFMpegHandler_ReadThread_MAX_PRIORITY
#define org_ffmpeg_service_FFMpegHandler_ReadThread_MAX_PRIORITY 10L
#ifdef __cplusplus
}
#endif
#endif
/* Header for class org_ffmpeg_service_FFMpegHandler_ReplyThread */

#ifndef _Included_org_ffmpeg_service_FFMpegHandler_ReplyThread
#define _Included_org_ffmpeg_service_FFMpegHandler_ReplyThread
#ifdef __cplusplus
extern "C" {
#endif
#undef org_ffmpeg_service_FFMpegHandler_ReplyThread_MIN_PRIORITY
#define org_ffmpeg_service_FFMpegHandler_ReplyThread_MIN_PRIORITY 1L
#undef org_ffmpeg_service_FFMpegHandler_ReplyThread_NORM_PRIORITY
#define org_ffmpeg_service_FFMpegHandler_ReplyThread_NORM_PRIORITY 5L
#undef org_ffmpeg_service_FFMpegHandler_ReplyThread_MAX_PRIORITY
#define org_ffmpeg_service_FFMpegHandler_ReplyThread_MAX_PRIORITY 10L
#ifdef __cplusplus
}
#endif
#endif
