/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_quanta_qtalk_media_video_H264EncodeTransform */

#ifndef _Included_com_quanta_qtalk_media_video_H264EncodeTransform
#define _Included_com_quanta_qtalk_media_video_H264EncodeTransform
#ifdef __cplusplus
extern "C" {
#endif
#undef com_quanta_qtalk_media_video_H264EncodeTransform_DEFAULT_ID
#define com_quanta_qtalk_media_video_H264EncodeTransform_DEFAULT_ID 109L
/*
 * Class:     com_quanta_qtalk_media_video_H264EncodeTransform
 * Method:    _Start
 * Signature: (Lcom/quanta/qtalk/media/video/IVideoSink;III)I
 */
JNIEXPORT jint JNICALL Java_com_quanta_qtalk_media_video_H264EncodeTransform__1Start
  (JNIEnv *, jclass, jobject, jint, jint, jint);

/*
 * Class:     com_quanta_qtalk_media_video_H264EncodeTransform
 * Method:    _Stop
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_quanta_qtalk_media_video_H264EncodeTransform__1Stop
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_quanta_qtalk_media_video_H264EncodeTransform
 * Method:    _OnMedia
 * Signature: (ILjava/nio/ByteBuffer;IJS)V
 */
JNIEXPORT void JNICALL Java_com_quanta_qtalk_media_video_H264EncodeTransform__1OnMedia
  (JNIEnv *, jclass, jint, jobject, jint, jlong, jshort);

#ifdef __cplusplus
}
#endif
#endif
