/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_quanta_qtalk_media_audio_SpeexEncoderTransform */

#ifndef _Included_com_quanta_qtalk_media_audio_SpeexEncoderTransform
#define _Included_com_quanta_qtalk_media_audio_SpeexEncoderTransform
#ifdef __cplusplus
extern "C" {
#endif
#undef com_quanta_qtalk_media_audio_SpeexEncoderTransform_DEFAULT_ID
#define com_quanta_qtalk_media_audio_SpeexEncoderTransform_DEFAULT_ID 97L
#undef com_quanta_qtalk_media_audio_SpeexEncoderTransform_mInFormat
#define com_quanta_qtalk_media_audio_SpeexEncoderTransform_mInFormat 255L
#undef com_quanta_qtalk_media_audio_SpeexEncoderTransform_mOutFormat
#define com_quanta_qtalk_media_audio_SpeexEncoderTransform_mOutFormat 97L
#undef com_quanta_qtalk_media_audio_SpeexEncoderTransform_mCompression
#define com_quanta_qtalk_media_audio_SpeexEncoderTransform_mCompression 6L
/*
 * Class:     com_quanta_qtalk_media_audio_SpeexEncoderTransform
 * Method:    _Start
 * Signature: (Lcom/quanta/qtalk/media/audio/IAudioSink;III)I
 */
JNIEXPORT jint JNICALL Java_com_quanta_qtalk_media_audio_SpeexEncoderTransform__1Start
  (JNIEnv *, jclass, jobject, jint, jint, jint);

/*
 * Class:     com_quanta_qtalk_media_audio_SpeexEncoderTransform
 * Method:    _Stop
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_quanta_qtalk_media_audio_SpeexEncoderTransform__1Stop
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_quanta_qtalk_media_audio_SpeexEncoderTransform
 * Method:    _OnMedia
 * Signature: (I[SIJ)V
 */
JNIEXPORT void JNICALL Java_com_quanta_qtalk_media_audio_SpeexEncoderTransform__1OnMedia
  (JNIEnv *, jclass, jint, jshortArray, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
