/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_quanta_qtalk_sr2_SR2_SoundClient */

#ifndef _Included_com_quanta_qtalk_sr2_SR2_SoundClient
#define _Included_com_quanta_qtalk_sr2_SR2_SoundClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_quanta_qtalk_sr2_SR2_SoundClient
 * Method:    SPEEXInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_quanta_qtalk_sr2_SR2_1SoundClient_SPEEXInit
  (JNIEnv *, jobject);

/*
 * Class:     com_quanta_qtalk_sr2_SR2_SoundClient
 * Method:    SpeexEchoCapture
 * Signature: ([S[S)V
 */
JNIEXPORT void JNICALL Java_com_quanta_qtalk_sr2_SR2_1SoundClient_SpeexEchoCapture
  (JNIEnv *, jobject, jshortArray, jshortArray);

/*
 * Class:     com_quanta_qtalk_sr2_SR2_SoundClient
 * Method:    SPEEXDestory
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_quanta_qtalk_sr2_SR2_1SoundClient_SPEEXDestory
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
